## Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: 

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

Original Array: [10 20 30 40 50]


## a) Addition of 2 in all the element  

In [3]:
add_result = arr + 2
print("After adding 2:", add_result)

After adding 2: [12 22 32 42 52]


## b) Multiply 3 with all the elements 

In [4]:
mul_result = arr * 3
print("After multiplying by 3:", mul_result)

After multiplying by 3: [ 30  60  90 120 150]


## c) Divide every element by 2 

In [5]:
div_result = arr / 2
print("After dividing by 2:", div_result)

After dividing by 2: [ 5. 10. 15. 20. 25.]


## Q.2 Questions on Basic NumPy Array: 

## a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [6]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

Reversed Array: [5 4 6 3 2 1]


## b) Find the most frequent value and their indice(s) in the following arrays: 
## i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 

In [8]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals_x, counts_x = np.unique(x, return_counts=True)
most_freq_x = vals_x[np.argmax(counts_x)]
indices_x = np.where(x == most_freq_x)[0]
print(f"Most frequent in x: {most_freq_x}, Indices: {indices_x}")

Most frequent in x: 1, Indices: [0 5 7 8 9]


## ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [9]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals_y, counts_y = np.unique(y, return_counts=True)
most_freq_y = vals_y[np.argmax(counts_y)]
indices_y = np.where(y == most_freq_y)[0]
print("Most frequent in y:", most_freq_y, ", Indices:", indices_y)

Most frequent in y: 1 , Indices: [0 1 2]


## Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: 
## a) Access 1st row, 2nd column  

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
elem_a = arr[0, 1]
print(elem_a)

20


## b) Access 3rd row, 1st column 

In [14]:
elem_b = arr[2, 0]
print(elem_b)

70


## Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute? 

In [16]:
import numpy as np
shreya_sharma = np.linspace(10, 100, 25)
print("Dimensions (ndim):", shreya_sharma.ndim)
print("Shape:", shreya_sharma.shape)
print("Total elements (size):", shreya_sharma.size)
print("Data type (dtype):", shreya_sharma.dtype)
print("Bytes consumed (nbytes):", shreya_sharma.nbytes)
transposed_reshape = shreya_sharma.reshape(25, 1) 
print(shreya_sharma.reshape(1, 25))
print("\nCan we use .T attribute directly on 1-D array?", shreya_sharma.T)

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Bytes consumed (nbytes): 200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Can we use .T attribute directly on 1-D array? [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


## Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>. 

In [17]:
ucs420_shreya_sharma = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(np.mean(ucs420_shreya_sharma))
print(np.median(ucs420_shreya_sharma))
print(np.max(ucs420_shreya_sharma))
print(np.min(ucs420_shreya_sharma))
print(np.unique(ucs420_shreya_sharma))
reshaped_ucs420_shreya_sharma = ucs420_shreya_sharma.reshape(4, 3)
print(reshaped_ucs420_shreya_sharma)
resized_ucs420_shreya_sharma = np.resize(ucs420_shreya_sharma, (2, 3))
print(resized_ucs420_shreya_sharma)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
